flaskr/contact/views.py
from flask import Blueprint, render_template

contact_bp = Blueprint('contact', __name__, url_prefix='/contact')

@contact_bp.route('')
def contact():
    return render_template('contact/contact.html')
  

flaskr/login/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user
from flaskr.forms import LoginForm
from flaskr.models import User

login_bp = Blueprint('login', __name__, url_prefix='/login')

@login_bp.route('', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_email(form.email.data)
        if user and user.validate_password(form.password.data):
            login_user(user, remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        elif not user:
            flash('This user does not exist.')
        elif not user.validate_password(form.password.data):
            flash('Your email address or password is not correct.')
    return render_template('login/login.html', form=form)

flaskr/logout/views.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_required, logout_user

logout_bp = Blueprint('logout', __name__, url_prefix='/logout')

@logout_bp.route('')
@login_required
def logout():
    logout_user()
    return redirect(url_for('app.home'))

flaskr/register/views.py
from flask import Blueprint, request, render_template, redirect, url_for
from flaskr.forms import RegisterForm
from flaskr.models import User

register_bp = Blueprint('register', __name__, url_prefix='/register')

@register_bp.route('', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            email = form.email.data,
            username = form.username.data,
            password = form.password.data
        )
        user.add_user()
        return redirect(url_for('login.login'))
    return render_template('register/register.html', form=form)

flaskr/search/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flaskr.models import Album, Artist
from flaskr.forms import SearchForm

search_bp = Blueprint('search', __name__, url_prefix='/search')

@search_bp.route('', methods=['GET', 'POST'])
def search():
    albums = Album.query.all()
    artists = Artist.query.all()
    form = SearchForm(request.form)

    if request.method == 'POST' and form.validate():
        keyword = form.keyword.data
    return render_template('search/search.html', albums=albums, artists=artists, form=form)

flaskr/signup/views.py
from flask import Blueprint, request, render_template, redirect, url_for
from flaskr.forms import RegisterForm
from flaskr.models import User
from flaskr import db

signup_bp = Blueprint('signup', __name__, url_prefix='/signup')

@signup_bp.route('', methods=['GET', 'POST'])
def signup():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            email = form.email.data,
            username = form.username.data,
            password = form.password.data
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        return redirect(url_for('login.login'))
    return render_template('signup/signup.html', form=form)

flaskr/user/views.py
from datetime import datetime

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flaskr.models import User, LikeAlbum, LikeSong, Album, Artist
from flaskr.forms import UserForm
from flaskr import db

from config import storage

user_bp = Blueprint('user', __name__, url_prefix='/user')

@user_bp.route('', methods=['GET', 'POST'])
@login_required
def user():
    like_albums = LikeAlbum.query.all()
    like_songs = LikeSong.query.all()
    
    albums = Album.query.all()
    artists = Artist.query.all() 

    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            file = request.files[form.picture_path.name].read()
            if file:
                file_name = user_id + '_' + \
                    str(int(datetime.now().timestamp())) + '.jpg'
                picture_path = 'flaskr/static/image_user/' + file_name
                open(picture_path, 'wb').write(file)
                # Upload
                storage.child(f"image_user/{file_name}").put(f"flaskr/static/image_user/{file_name}")
                # Download
                user.picture_path = storage.child(f"image_user/{file_name}").get_url(f"flaskr/static/image_user/{file_name}")
                print("---------------")
                print(user.picture_path)
        db.session.commit()
        return redirect(url_for('user.user'))
        flash('User info update completed.')
    return render_template('user/user.html', like_albums=like_albums, like_songs=like_songs, albums=albums, artists=artists, form=form)

flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)| safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="theme-color" content="#3dbaf4" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ayumi Tanaka">
    <meta name="generator" content="Visual Studio Code">
    <meta name="description" content="A web app for people who love Japanese City Pop">
    <meta name="keywords" content="citypop, city pop, Tatsuro Yamashita, Mariya Takeuchi, Ayumi Tanaka">
    <!-- OGP -->
	<meta property="og:type" content="website">
	<meta property="og:title" content="Japanese City Pop">
	<meta property="og:image:alt" content="Japanese City Pop">
    <meta property="og:site_name" content="Japanese City Pop">
	<meta property="og:url" content="https://japanese-city-pop.herokuapp.com/">
    <meta name="image" property="og:image" content="https://japanese-city-pop.herokuapp.com/static/image/ogp.png">
	<meta property="og:description" content="A web app for people who love Japanese City Pop">
    <!-- Twitter -->
    <meta name="twitter:site" content="@ayumitanaka_13">
    <meta name="twitter:title" content="Japanese City Pop">
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="japanese-city-pop.herokuapp.com">
    <meta name="twitter:url" content="https://japanese-city-pop.herokuapp.com">
    <meta name="twitter:image" content="https://japanese-city-pop.herokuapp.com/static/image/ogp.png">
    <meta name="twitter:description" content="A web app for people who love Japanese City Pop">
    <!-- CSS -->
    <!-- <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="/static/css/public/style.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/static/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/static/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/favicon/ms-icon-144x144.png">
    <!-- Title -->
    <title>Japanese City Pop</title>
</head>

<body class="bg-purple-300" id="top">
    {% block content %}

    {% block header %}
    <header>
        <nav>
            <!-- search -->
            <ul>
                <li>
                    <a class="menu-block" href="{{ url_for('search.search') }}">
                        <i class="fas fa-search mr-2"></i>Search
                    </a>
                </li>
            </ul>            
            <!-- toggle -->
            <div class="block lg:hidden">
                <button id="nav-toggle" class="btn-toggle">
                    <svg class="svg-style" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
                    </svg>
                </button>
            </div>
            <!-- nav bar -->
            <div class="nav-bar-style" id="nav-content">
                <ul class="nav-ul-style">
                    <li class="menu-ml lg:ml-0">
                        <a class="menu-block" href="{{ url_for('app.home') }}">Home</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('history.history') }}">History</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('artist.artist') }}">Artist</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('logout.logout')}}">Logout</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('user.user')}}">User</a>
                    </li>
                    {% else %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('signup.signup')}}">Sign up</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('login.login')}}">Login</a>
                    </li>
                    {% endif %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('contact.contact') }}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    {% endblock %}

    {% block header2 %}
    <header class="header-style">
        <nav class="pt-4 lg:pt-6">
            <!-- search -->
            <ul>
                <li>
                    <a class="menu-block" href="{{ url_for('search.search') }}">
                        <i class="fas fa-search mr-2"></i>Search
                    </a>
                </li>
            </ul>            
            <!-- toggle -->
            <div class="block lg:hidden">
                <button id="nav-toggle" class="btn-toggle">
                    <svg class="svg-style" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
                    </svg>
                </button>
            </div>
        <!-- nav bar -->
            <div class="nav-bar-style" id="nav-content">
                <ul class="nav-ul-style">
                    <li class="menu-ml lg:ml-0">
                        <a class="menu-block" href="{{ url_for('app.home') }}">Home</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('history.history') }}">History</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('artist.artist') }}">Artist</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('logout.logout')}}">Logout</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('user.user')}}">User</a>
                    </li>
                    {% else %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('signup.signup')}}">Sign up</a>
                    </li>
                    <li class="menu-ml">
                        <a class="menu-block" href="{{url_for('login.login')}}">Login</a>
                    </li>
                    {% endif %}
                    <li class="menu-ml">
                        <a class="menu-block" href="{{ url_for('contact.contact') }}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>    
    {% endblock %}

    {% block bg %}
    <div class="bg-style" style="background-image: linear-gradient(135deg, rgba(255, 147, 205, 0.3), rgba(61, 186, 244, 0.3)), url(/static/image/neon.jpeg)">
    {% endblock %}

    {% block back %}
    <div class="btn-back-style">
        <a href="#top">
            <p class="btn-back">
                <i class="fas fa-angle-double-up"></i>
            </p>
        </a>
    </div>
    {% endblock %}

    {% endblock %}

    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/4538f04da3.js" crossorigin="anonymous"></script>   
    <!-- javascript -->
    <script src="/static/js/index.js"></script>

</body>
</html>

flaskr/templates/comingsoon.html
{% extends "base.html" %}
{% block content %}

<div class="base-style">
    {% block header %}
    {{ super() }}
    {% endblock %}

    {% block bg %}
    {{ super() }}
    {% endblock %}

        <h1 class="subtitle">Coming Soon</h1>
    </div>
</div>

{% endblock %}

flaskr/templates/contact.html
{% extends "base.html" %}
{% block content %}

<!-- more -->
<div class="h-screen w-screen pt-8 md:pt-10 xl:pt-20 box sticky top-0">
    <div class="flex justify-center box">
        <h1 class="text-2xl text-center font-black box">scroll me</h1>
    </div>
</div>

<!-- footer -->
<div class="h-screen w-screen box flex items-end  pt-8 md:pt-10 xl:pt-20">
    <div class="h-full w-full justify-center items-end bg-cover bg-center bg-no-repeat box flex md:mt-5 sticky top-0" style="background-image: linear-gradient(rgba(255, 255, 255, 0), rgba(130, 110, 210, 0.5)), url(/static/image/neon7.png);">
        <div class="text-center">
            <h1 class="text-4xl font-black mb-8 box">\ THANK YOU /</h1>
            <h1 class="text-2xl font-black mb-4">feel free to contact me</h1>
            <h1 class="text-2xl font-black mb-8">&copy; 2020 <a href="https://ayumitanaka.net">Ayumi Tanaka</a></h1>
        </div>
    </div>
</div>
{% endblock %}

flaskr/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="base-style">
    {% block header %}
    {{ super() }}
    {% endblock %}

    {% block bg %}
    {{ super() }}
    {% endblock %}
    
        <h1 class="title">JAPANESE CITY POP</h1>
    </div>
</div>

{% endblock %}

flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}

<div class="h-screen w-screen p-8 md:p-12 md:py-20 xl:p-20 box">
    <div class="h-full w-full flex items-center justify-center bg-cover bg-center bg-no-repeat shadow-lg rounded-lg" style="background-image: linear-gradient(135deg, rgba(255, 147, 205, 0.3), rgba(61, 186, 244, 0.3)), url(/static/image/neon5.jpeg)">
        <div class="w-1/3 box">
            <h1 class="text-7xl lg:text-8xl text-center font-black box animate-pulse">Sign In</h1>
            <div class="flex items-center justify-center bg-white bg-opacity-30 rounded mt-8 py-16">
                <form method="POST" class="box">
                    {{form.csrf_token}}
                    <h4 class="text-lg sm:text-3xl xl:text-3xl">
                        {{render_field(form.email)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-4">
                        {{render_field(form.password)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-8">
                        {{form.submit()}}
                    </h4>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block content %}

<div class="h-screen w-screen p-8 md:p-12 md:py-20 xl:p-20 box">
    <div class="h-full w-full flex items-center justify-center bg-cover bg-center bg-no-repeat shadow-lg rounded-lg" style="background-image: linear-gradient(135deg, rgba(255, 147, 205, 0.3), rgba(61, 186, 244, 0.3)), url(/static/image/neon5.jpeg)">
        <div class="w-1/3 box">
            <h1 class="text-7xl lg:text-8xl text-center font-black box animate-pulse">Sign Up</h1>
            <div class="flex items-center justify-center bg-white bg-opacity-30 rounded mt-8 py-16">
                <form method="POST" class="text-gray-100 box">
                    {{form.csrf_token}}
                    <h4 class="text-lg sm:text-3xl xl:text-3xl">
                        {{render_field(form.username)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-4">
                        {{render_field(form.email)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-4">
                        {{render_field(form.password)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-4">
                        {{render_field(form.password_confirm)}}
                    </h4>
                    <h4 class="text-lg sm:text-3xl xl:text-3xl mt-8">
                        {{form.submit()}}
                    </h4>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

flaskr/templates/user.html
{% extends "base.html" %}
{% block content %}
<div class="h-screen w-screen p-8 md:p-12 md:py-20 xl:p-20 box">
    <div class="h-full w-full flex items-center justify-center bg-cover bg-center bg-no-repeat shadow-lg rounded-lg" style="background-image: linear-gradient(135deg, rgba(255, 147, 205, 0.3), rgba(61, 186, 244, 0.3)), url(/static/image/neon5.jpeg)">
        <div class="w-1/2 box">
            {% if current_user.is_authenticated %}
            <h1 class="text-7xl lg:text-8xl text-center font-black box animate-pulse">Hello, {{current_user.username}}</h1>
            {% else %}
            <p>Sign in or Sign up</p>
            {% endif %}
            <div class="flex items-center justify-center bg-white bg-opacity-30 rounded mt-8 py-16">
                <h4 class="text-lg sm:text-3xl xl:text-3xl">
                    My Favorites
                </h4>
            </div>
        </div>
    </div>
</div>

{% endblock %}